### ISSUE TITLE
[ISSUE-1] Converting problem

### ISSUE THREAD

**Issue by apat1n** [maybe-hello-world/RainbowDQN#1]
```
Traceback (most recent call last):
  File "C:/projects/RainbowDQN/main.py", line 18, in <module>
    results, losses = agent.train(5000)
  File "C:\projects\RainbowDQN\Rainbow\agent.py", line 158, in train
    loss = self.replay()
  File "C:\projects\RainbowDQN\Rainbow\agent.py", line 85, in replay
    dones = torch.from_numpy(dones).float()
TypeError: can't convert np.ndarray of type numpy.bool_. The only supported types are: double, float, float16, int64, int32, and uint8.
```

**Comment by maybe-hello-world** [comment]
Resolved by #2
